networks:
  proxy:
    external: true

volumes:
  portainer-data:
   external: true

services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer-ce
    networks:
      - proxy
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.constraint-label=proxy
      - traefik.http.routers.portainer-http.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.routers.portainer-http.entrypoints=http
      - traefik.http.routers.portainer-http.middlewares=https-redirect
      - traefik.http.routers.portainer-https.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.routers.portainer-https.entrypoints=https
      - traefik.http.routers.portainer-https.tls=true
      - traefik.http.routers.portainer-https.tls.certresolver=le
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    restart: unless-stopped